# Auto-generated from data/DATA.TWT/POWERUP.TXT.
# Powerup id -> description (the text shown on-screen when triggered).

POWERUP_NAMES = {
      0: 'n/a',
      1: 'n/a',
      2: 'Pedestrians with greased shoes!',
      3: 'Giant pedestrians!',
      4: 'Explosive pedestrians!',
      5: 'Hot rod!',
      6: 'Turbo pedestrians!',
      7: 'Invulnerability!',
      8: 'Free repairs!',
      9: 'Instant repair!',
     10: 'Timer frozen!/Timer thaw!/',
     11: 'Underwater ability!',
     12: 'Time bonus',
     13: 'Oh dear, bodywork trashed!',
     14: 'n/a',
     15: 'Frozen opponents!',
     16: 'Frozen cops!',
     17: 'Turbo opponents!',
     18: 'Turbo cops!',
     19: 'Lunar Gravity...',
     20: 'Pinball mode!',
     21: 'Wall climber!',
     22: 'Bouncey bouncey!',
     23: 'Oh dear, jelly suspension!',
     24: 'Pedestrians shown on map',
     25: 'Pedestrian Electro-bastard Ray',
     26: 'Greased tyres!',
     27: 'Acme Damage Magnifier!',
     28: 'n/a',
     29: 'n/a',
     30: 'n/a',
     31: 'n/a',
     32: 'Instant handbrake!',
     33: 'Immortal Pedestrians',
     34: 'Turbo!',
     35: 'Mega-turbo!',
     36: 'Stupid pedestrians',
     37: 'Suicidal pedestrians',
     38: '5 Free recovery vouchers',
     39: 'Solid granite car!',
     40: 'Rock springs!',
     41: 'Drugs!!!',
     42: 'Grip-o-matic tyres!',
     43: 'Peds with stupid heads!',
     44: 'Mutant Corpses!',
     45: 'Gravity from jupiter!',
     46: 'n/a',
     47: 'SLOW-MOTION PEDESTRIANS!',
     48: 'MiniAture Pedestrians!',
     49: 'mEGA Turbo Nitrus!',
     50: "Got 'im  in the bollocks!",
     51: 'Afterburner!',
     52: 'Mine shitting ability!',
     53: 'Oil slick SHITTING ABILITY!',
     54: 'Kangaroo on command!',
     55: 'Pedestrian annihilator!',
     56: 'Opponent repulsificator!',
     57: 'Dismemberfest!',
     58: 'Ethereal pedestrians!',
     59: "Groovin' Pedestrians!",
     60: 'Pedestrian Panic!',
     61: 'Helium Filled Pedestrians!',
     62: 'DRUNK pedestrians!',
     63: 'Fat Bastards!',
     64: 'Stick insects!',
     65: 'Pedestrian repulsificator!',
     66: 'Extra armour',
     67: 'Extra power',
     68: 'Extra offensive',
     69: 'Extra everything',
     70: 'Double extra armour',
     71: 'Double extra power',
     72: 'Double extra offensive',
     73: 'Double extra everything',
     74: 'Max armour!',
     75: 'Max power!',
     76: 'Max offensive!',
     77: 'Max everything!',
     78: 'Extra armour slot',
     79: 'Extra power slot',
     80: 'Extra offensive slot',
     81: 'Extra slots all round',
     82: 'Bonus armour slots',
     83: 'Bonus power slots',
     84: 'Bonus offensive slots',
     85: 'Bonus slots all round',
     86: 'n/a',
     87: 'n/a',
     88: 'n/a',
     89: 'n/a',
     90: 'DrUnk Driving',
     91: 'Pedestrian Flame-thrower!',
     92: 'Pedestrian Valium',
     93: 'Powerup cancellificatinizer',
     94: 'WOW! A MUTANT TAIL THING!',
     95: 'SEVER TAIL',
     96: 'Slaughter Mortar',
     97: 'Cloaking Device',
}
